#!/bin/bash

VIDEO_ID=$1
TMP_DIR=/tmp/${VIDEO_ID}
OUTPUT=${TMP_DIR}/${VIDEO_ID}.mp4
BUCKET=$2
PREFIX=$3
S3_PATH=s3://${BUCKET}/${PREFIX}/${OUTPUT}

mkdir -p ${TMP_DIR}
annie -p -o ${TMP_DIR} -O ${VIDEO_ID} ${VIDEO_ID}

TMP_FILE=${TMP_DIR}/$(ls ${TMP_DIR} | grep ${VIDEO_ID} | awk '{print $1}')
ffmpeg -y -i ${TMP_FILE} -c:a copy -c:v copy ${OUTPUT}
aws s3 cp ${OUTPUT} ${S3_PATH} --no-progress
rm -rf ${TMP_DIR}
