version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1

jobs:
    - build:
        repo: nogi-backup
        tag: 'latest'
        no-output-timeout: 15m

workflows:
    main:
        jobs:
            - build
