version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1

workflows:
    simple_build_and_push:
        jobs:
            - aws-ecr/build-and-push-image:
                repo: nogi-backup-worker
                tag: 'latest'